CREATE DATABASE hospital;

CREATE USER 'HospitalAdmin'
  IDENTIFIED BY 'z3OimAwtpmBNQ4Yb';

  GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON  `hospital`.* TO 'HospitalAdmin'@'%';

  CREATE TABLE `hospital`.`historySearch` ( `id` INT(10) NOT NULL AUTO_INCREMENT , `userHistory` VARCHAR(30) NOT NULL , `dateHistory` VARCHAR(30) NOT NULL , `timeHistory` VARCHAR(30) NOT NULL , `querySearchHistory` VARCHAR(30) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

  CREATE TABLE `hospital`.`patient` ( `id` INT(10) NOT NULL AUTO_INCREMENT , `Surname` VARCHAR(30) NOT NULL , `Name` VARCHAR(30) NOT NULL , `Patronymic` VARCHAR(30) NOT NULL , `DOB` VARCHAR(30) NOT NULL , `Document` VARCHAR(30) NOT NULL , `ResidentialAddress` VARCHAR(30) NOT NULL , `DateInReceiver` VARCHAR(30) NOT NULL , `DateOutReceiverHospital` VARCHAR(30) NOT NULL , `HistoryNamber` VARCHAR(30) NOT NULL , `DepartmentIn` VARCHAR(30) NOT NULL ,   `DepartmentOut` VARCHAR(30) NOT NULL , `TypeMedicalHelp` VARCHAR(30) NOT NULL , `FinalDiagnosis` VARCHAR(30) NOT NULL , `WorkDescription` VARCHAR(30) NOT NULL , `Sity` VARCHAR(30) NOT NULL , `Phone` VARCHAR(30) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

  USE hospital;

  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '01.01.2001', '02.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '02.01.2001', '02.02.2001', '2', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '04.01.2001', '02.02.2001', '3', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '05.01.2001', '02.02.2001', '4', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '06.01.2001', '02.02.2001', '5', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '07.01.2001', '02.02.2001', '6', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '08.01.2001', '02.02.2001', '7', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '09.01.2001', '02.02.2001', '8', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '10.01.2001', '02.02.2001', '9', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '11.01.2001', '02.02.2001', '10', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '12.01.2001', '02.02.2001', '11', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '13.01.2001', '02.02.2001', '12', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '14.01.2001', '02.02.2001', '13', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '15.01.2001', '02.02.2001', '14', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '16.01.2001', '02.02.2001', '15', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '17.01.2001', '02.02.2001', '16', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '18.01.2001', '02.02.2001', '17', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '19.01.2001', '02.02.2001', '18', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '20.01.2001', '02.02.2001', '19', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '21.01.2001', '02.02.2001', '20', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '22.01.2001', '02.02.2001', '21', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '23.01.2001', '02.02.2001', '22', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '24.01.2001', '02.02.2001', '23', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '25.01.2001', '02.02.2001', '24', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '26.01.2001', '02.02.2001', '25', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ИВАНОВ', 'ИВАН', 'ИВАНОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 0', '27.01.2001', '02.02.2001', '26', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '01.01.2001', '02.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '02.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '03.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '04.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '05.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '06.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '07.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '08.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '09.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');
  INSERT INTO `patient` (`id`, `Surname`, `Name`, `Patronymic`, `DOB`, `Document`, `ResidentialAddress`, `DateInReceiver`, `DateOutReceiverHospital`, `HistoryNamber`, `DepartmentIn`, `DepartmentOut`, `TypeMedicalHelp`, `FinalDiagnosis`, `WorkDescription`, `Sity`, `Phone`) VALUES (NULL, 'ПЕТРОВ', 'ПЕТР', 'ПЕТРОВИЧ', '01.01.1900', 'AB123456', 'УЛ.ПУШКИНА-ДОМ 1', '10.01.2001', '18.02.2001', '1', 'ТРАВМАТОЛОГИЯ', 'НЕВРОЛОГИЯ', 'СТАЦИОНАР', 'I-10', '\"ОАО\"БЕЛОРУСКИЙ КОЛХОЗНИК\"', 'БРЕТС', '+37529 000 00 00');